### PR TITLE
Avoid UB: Use `MaybeUninit` instead of `ManuallyDrop` in `ScopeGuard`

### PR DESCRIPTION
**Pull request by willtunnels**
Doing a `ptr::read` of a guard value or dropfn containing a mutable reference is probably UB. Instead we can use `MaybeUninit` and `mem::replace`, which generates the same assembly but avoids potentially holding two mutable references to the same memory.

### CODE REVIEW

**Comment by bluss** [comment]
ptr::read in itself I can't see how it is UB, is there an explanation about ptr::read and what subsequent access or other thing that breaks a Rust rule?

I would suggest that this change is not needed. However, a different cleanup that would make me happy would be to replace the use of `forget` seen in the present code with `ManuallyDrop` (in today's Rust we prefer this safer idiom of first putting a value in manuallydrop, instead of forgetting it after the fact).

**Comment by willtunnels** [comment]
I believe that the `ptr::read` breaks Rust's [rules of references](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html#the-rules-of-references) if `ScopeGuard` is parameterized by certain choices of `T`.

According to the [docs](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html), `ManuallyDrop` "has no effect on the assumptions that the compiler makes about its content." So, for our purposes, we can treat `guard.value` as a `T` instead of a `ManuallyDrop<T>`. 

Now suppose `T` is `&mut U` for some `U`. On line 458, where `S::should_run()` is called, `guard.value` is an `&mut U` to the same memory as `value`.

**Comment by willtunnels** [comment]
While I'm pretty sure that there is potential UB here--though you could convince me otherwise of course--I would also argue that if there is non-trivial uncertainty over whether the current implementation is UB, it is better to switch to using `MaybeUninit`. Based on some experiments on Rust playground, it doesn't seem like it should lead to any performance degradation, except possibly where the compiler was relying on UB of course :).

**Comment by bluss** [comment]
Can we compare with ManuallyDrop::take https://doc.rust-lang.org/1.53.0/src/core/mem/manually_drop.rs.html#91 ? We seem to do the same thing - move out of the manuallydrop and not use the manuallydrop itself further. This is the common practice. Using MaybeUninit and moving in an uninit value instead of just leaving the place we're reading from untouched is a worse option IMO and smells of something of a misunderstanding, that we need to move and that `ptr::read` would not be correct. Compare with `ManuallyDrop::take` which also uses ptr::read.

`should_run` is a static method (does not have a self receiver) so I don't see how it is an access or anything - so I would look for a different proposed access that creates a rule violating situation.

**Comment by willtunnels** [comment]
I'm not saying `should_run` is causing the UB, though I think my post made that unclear. I just made mentioned it because it is after the point in the program where you are holding two mutable references to the same memory. Consider this code:
```rust
  use std::{ptr, mem::ManuallyDrop};
  struct S {};
  let mut a: S = S{};
  let b: ManuallyDrop<&mut S> = ManuallyDrop::new(&mut a);
  let c: &mut S = unsafe { ptr::read(&*b) };
```
This is essentially what the `ScopeGuard` is doing. Note that `b` and `c` are mutable references to the same memory. My impression was that holding two such references isnot allowed. It is possible that I am wrong, however, and you that have to actually use `b` while holding `c` for it to be UB.

The safety contract for `ManuallyDrop::take` says:
> This function semantically moves out the contained value without preventing further usage, leaving the state of this container unchanged. It is your responsibility to ensure that this `ManuallyDrop` is not used again.
That safety contract isn't incompatible with my originally interpretation, but has the implication that the latter thing is true.

**Comment by bluss** [comment]
IMO it's ok that b and c are both references to the same memory. Because `b` is not used after `c` is created. I think the following is similar:

```
let mut x = 1;
let b = &mut x;
let c = &mut *b;
```

B and C are references to the same memory, isn't it very similar? This kind of scoping is "easy" when Rust keeps track of it, but it gets confusing quickly with unsafe code and raw pointers. But inside certain rules, we are certainly allowed to derive and active pointer and use it (while other pointers are in scope but not active).

Aliasing is when we interleave reading and writing to the same place through different pointers. I don't think we do that here, but it's good to scrutinize, especially looking at the exit paths from a function that are not readily apparent (panic etc).

**Comment by bluss** [comment]
> It is possible that I am wrong, however, and you that have to actually use `b` while holding `c` for it to be UB.

Note that in Rust, even this compiles:

```rust
fn main() {
    let mut x = 1;
    let b = &mut x;
    let c = &mut *b;
    *b = 2;
}
```

We are "holding c" by having it in scope. But the borrow checker of course limits its scope - c is only active after it is created and ends its activity before the write through `b`. It's only if we try add a line like this: `*c = 3;` at the end, that we get a compile-time error: This would be when we're actually interleaving the periods the different pointers to the same memory are active.

**Comment by willtunnels** [comment]
Yes, I see that you're right now. I wasn't thinking clearly about the borrowing rules. Sorry for the confusion on my end.

I'd be happy to make that other refactor you mentioned. I'll make a different pull request for that.

**Pull request closed without merging**
