### PR TITLE
Add function handle_panic_of() that runs a closure only if another closure panics.

### PR DESCRIPTION
**Pull request by tormol**
I needed this when writing some unsafe code that calls passed closures in the middle.

### CODE REVIEW

**Comment by tormol** [comment]
Updated to specify **unwinding** abort.

**Comment by bluss** [comment]
Thanks. I'm sorry I'm a bit undecided about this one, if scopeguard should really add a function for this (and what to name it).

**Comment by tormol** [comment]
While this function diverges from the current purpose of this crate, "make sure this code runs",
 it is still related: "run stuff on unwind".

I (use)[https://github.com/tormol/map_in_place/blob/master/lib.rs#L169] this function because `handle_panic_of(|| f(x), || {/*cleanup*/} )` expresses the intent better than
```
let g = guard((), |_| {/*cleanup*/} );
f(x);
mem::forget(g);
```

I looked at the other reverse dependencies on crates.io to see if they do anything similar, but they only use `defer!()`. On the other hand they only have a third of this crates downloads.


I propose the function should be renamed to `handle_unwind_of`.

**Comment by bluss** [comment]
What about this instead?

```rust
defer_panic! {
  /* expression */
}
```

It's just like the existing `defer` but it only runs if the scope is exited through a panic.

**Comment by tormol** [comment]
Closing because [`defer_on_unwind!()`](https://github.com/bluss/scopeguard/pull/10) is an actual scope guard.

**Pull request closed without merging**
