### PR TITLE
Fixes to prepare for next release

### LINKED ISSUE #15: Document why guard closure is FnMut, not FnOnce
The documentation states that

> The guard's closure will be called with a mut ref to the held value in the destructor. It's called only once.

yet `ScopeGuard` takes an `F where F: FnMut(&mut T)`. What is the reason for not allowing `F` to be `FnOnce`?

### PR DESCRIPTION
**Pull request by bluss**
Various style cleanups and documentation edits to follow up on #16.

Closes #15

### CODE REVIEW

**Comment by bluss** [comment]
@Amanieu any thoughts on how important it is to make the next release 1.0? Or just continue with the versions (0.4).

**Comment by Amanieu** [comment]
Hmm, I think the only concern I have right now is whether we want `into_inner` to return the closure or not. In practice I can't think of any use case for this, so it might be better to only return the wrapped object.

There should also be a note in the docs on how to simulate the OnUnwind strategy in no_std mode by using `mem::forget` or `into_inner` to manually defuse a guard at the end of a scope.

Other those two points, I don't think that there is anything left to add to scopeguard: it is a fairly straightforward crate. So it should be fine to make the next release 1.0.

**Comment by bluss** [comment]
Good points! I agree about skipping the closure.

**Comment by tormol** [comment]
I agree with making into_inner() a static function and not returning the closure.

When I made the commit to expose `_on_success`, I had forgotten [my own argument against the name](https://github.com/bluss/scopeguard/pull/10#issuecomment-266283386):astonished:! I don't have a better name though, so making it public is fine (especially since the changelog is already written).

Since I wrote the commit to fix the clippy lints, `inline_always` has been made opt in, and `feature="cargo_clippy"` has also been obsoleted by tool attributes. I'll open a PR to remove that one line.

**Comment by tormol** [comment]
The only missing feature I can think of is `const fn`, but that is blocked on trait bounds and `unsafe`

Expanded and reworded changelog:

```rst
  - Change the closure type from ``FnMut(&mut T)`` to ``FnOnce(T)``:
    Passing the inner value by value instead of a mutable reference is a
    breaking change, but allows the guard closure to consume it. (by @tormol)
  - Add ``defer_on_success!{}``, ``guard_on_success()`` and ``OnSuccess``
    strategy, which triggers when scope is exited *without* panic. It's the
    opposite to ``OnUnwind`` / ``guard_on_unwind()`` / ``defer_on_unwind!{}``.
  - Add ``ScopeGuard::into_inner()``, which "defuses" the guard and returns the
    guarded value. (by @tormol)
  - Implement ``Sync`` for guards with non-``Sync`` closures.
  - Require Rust 1.20
 ```

**Pull request merged**
