### PR TITLE
Setup CI with GitHub Actions

### LINKED ISSUE #27: Add github actions for CI
We need github actions so that we can check PRs and also consciously track the MSRV. Stretch goal is to test no-std support, too.

### PR DESCRIPTION
**Pull request by konsumlamm**
Closes #27.

### CODE REVIEW

**Comment by Amanieu** [comment]
It would be nice to have a rustfmt check as well.

**Comment by Amanieu** [comment]
Thanks!

**Comment by konsumlamm** [comment]
This actually fails on everything but stable, I'll try to fix that.

**Comment by bluss** [comment]
Thanks a lot for fixing.

**Pull request merged**
